apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-request
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Git
    tekton.dev/tags: SCM
    tekton.dev/displayName: "pull request"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
    ozone-in2tive-ai/imgurl: "/api/asset-bucket/taskicons/git.svg"
spec:
  description: >-
    This Task allows a user to interact with an SCM (source control management)
    system through an abstracted interface

    This Task works with both public SCM instances and self-hosted/enterprise GitHub/GitLab
    instances. In download mode, this Task will look at the state of an existing pull
    request and populate the pr workspace with the state of the pull request, including the
    .MANIFEST file. In upload mode, this Task will look at the contents of the pr workspace
    and compare it to the .MANIFEST file (if it exists).

  params:
    - name: mode
      type: string
      description: If "download", the state of the pull request at `url` will be fetched. If "upload" then the pull request at `url` will be updated.
    - name: url
      type: string
      description: The URL of the Pull Reuqest, e.g. `https://github.com/bobcatfish/catservice/pull/16`
    - name: provider
      type: string
      description: The type of SCM system, currently `github` or `gitlab`
    - name: secret-key-ref
      type: string
      description: The name of an opaque secret containing a key called "token" with a base64 encoded SCM token
    - name: insecure-skip-tls-verify
      type: string
      description: If "true", certificate validation will be disabled
      default: "false"
  workspaces:
    - name: pr
  steps:
    - name: pullrequest-init
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init" #tag: v0.20.1
      command: ["/ko-app/pullrequest-init"]
      env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.secret-key-ref)
              key: token
      args:
        - "-url"
        - "$(params.url)"
        - "-path"
        - "$(workspaces.pr.path)"
        - "-mode"
        - "$(params.mode)"
        - "-provider"
        - "$(params.provider)"
        - "-insecure-skip-tls-verify"
        - "$(params.insecure-skip-tls-verify)"
