apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-create-kubeconfig-pvc
spec:
  resources:
    requests:
      storage: 5M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-gke-cluster-
spec:
  taskRef:
    name: gke-cluster-create
  params:
  - name: project-name
    value: tekton-prow-14
  - name: private-key-path
    value: service-account.json
  - name: identifier
    value: try-it-out
  workspaces:
  - name: gcp-service-account
    secret:
      # This secret exists in the tekton-releases prow cluster
      secretName: test-account
  - name: kubeconfig
    persistentVolumeClaim:
      claimName: gke-create-kubeconfig-pvc