apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/displayName: "aws cli"
    tekton.dev/platforms: "linux/amd64"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This task performs operations on Amazon Web Services resources using aws.

  workspaces:
    - name: source
    - name: secrets
      mountPath: /tekton/home/.aws
  params:
    - name: SCRIPT
      description: The AWS script to run
      type: string
      default: "aws $@"
    - name: ARGS
      description: AWS cli arguments to be passed
      type: array
      default: ["help"]
  steps:
    - name: awscli
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/amazon/aws-cli:2.0.52" #tag: 2.0.52
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"