# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

required = [
  "github.com/tektoncd/plumbing/scripts",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/tektoncd/plumbing"
  non-go = false
