apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gke-deploy
spec:
  inputs:
    # resources:
    # - name: source-repo
    #   type: git
    params:
    - name: ARGS
      type: array
      description: gke-deploy CLI arguments to run
      default: ["--help"]
  steps:
  - name: gke-deploy
    image: gcr.io/cloud-builders/gke-deploy
    command: ["/gke-deploy"]
    args: ["$(inputs.params.ARGS)"]
