apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
    - name: maven-settings
  inputs:
    params:
      - name: GOALS
        description: maven goals to run
        type: array
        default:
          - "package"
      - name: MAVEN_MIRROR_URL
        description: The Maven bucketrepo- mirror
        type: string
        default: ""
      - name: PROXY_USER
        description: The username for the proxy server
        type: string
        default: ""
      - name: PROXY_PASSWORD
        description: The password for the proxy server
        type: string
        default: ""
      - name: PROXY_PORT
        description: Port number for the proxy server
        type: string
        default: ""
      - name: PROXY_HOST
        description: Proxy server Host
        type: string
        default: ""
      - name: PROXY_NON_PROXY_HOSTS
        description: Non proxy server host
        type: string
        default: ""
      - name: PROXY_PROTOCOL
        description: Protocol for the proxy ie http or https
        type: string
        default: "http"
    resources:
      - name: source
        type: git
        targetPath: /
  steps:
    - name: mvn-settings
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/usr/bin/env bash

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && \
        echo 'using existing $(workspaces.maven-settings.path)/settings.xml' && \
        cat $(workspaces.maven-settings.path)/settings.xml && exit 0

        cat > $(workspaces.maven-settings.path)/settings.xml <<EOF
        <settings>
          <mirrors>
            <!-- The mirrors added here are generated from environment variables. Don't change. -->
            <!-- ### mirrors from ENV ### -->
          </mirrors>
          <proxies>
            <!-- The proxies added here are generated from environment variables. Don't change. -->
            <!-- ### HTTP proxy from ENV ### -->
          </proxies>
        </settings>
        EOF

        xml=""
        if [ -n "$(inputs.params.PROXY_HOST)" -a -n "$(inputs.params.PROXY_PORT)" ]; then
          xml="<proxy>\
            <id>genproxy</id>\
            <active>true</active>\
            <protocol>$(inputs.params.PROXY_PROTOCOL)</protocol>\
            <host>$(inputs.params.PROXY_HOST)</host>\
            <port>$(inputs.params.PROXY_PORT)</port>"
          if [ -n "$(inputs.params.PROXY_USER)" -a -n "$(inputs.params.PROXY_PASSWORD)" ]; then
            xml="$xml\
                <username>$(inputs.params.PROXY_USER)</username>\
                <password>$(inputs.params.PROXY_PASSWORD)</password>"
          fi
          if [ -n "$(inputs.params.PROXY_NON_PROXY_HOSTS)" ]; then
            xml="$xml\
                <nonProxyHosts>$(inputs.params.PROXY_NON_PROXY_HOSTS)</nonProxyHosts>"
          fi
          xml="$xml\
              </proxy>"
          sed -i "s|<!-- ### HTTP proxy from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi

        if [ -n "$(inputs.params.MAVEN_MIRROR_URL)" ]; then
          xml="    <mirror>\
            <id>mirror.default</id>\
            <url>$(inputs.params.MAVEN_MIRROR_URL)</url>\
            <mirrorOf>central</mirrorOf>\
          </mirror>"
          sed -i "s|<!-- ### mirrors from ENV ### -->|$xml|" $(workspaces.maven-settings.path)/settings.xml
        fi

        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] && cat $(workspaces.maven-settings.path)/settings.xml
        [[ -f $(workspaces.maven-settings.path)/settings.xml ]] || echo skipping settings

    - name: mvn-goals
      image: gcr.io/cloud-builders/mvn
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - $(workspaces.maven-settings.path)/settings.xml
        - "$(inputs.params.GOALS)"