apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mypy-lint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality
    tekton.dev/tags: linter
    tekton.dev/displayName: "Mypy(Python) linter"
    tekton.dev/platforms: "linux/amd64"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This task can be used to perform lint check on python files
  workspaces:
    - name: shared-workspace
      description: A workspace containing files that we want to check
  params:
    - name: args
      type: array
      description: extra args that needs to be appended
      default: ["--help"]
  steps:
    - name: lint-python-files
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/cytopia/mypy:latest-0.2" #tag: latest-0.2
      workingDir: $(workspaces.shared-workspace.path)
      command:
        - mypy
      args:
        - $(params.args)
