apiVersion: v1
kind: ServiceAccount
metadata:
  name: boskos-heartbeat
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-editor
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: boskos-heartbeat-pod-editor
  namespace: default
subjects:
  - kind: ServiceAccount
    name: boskos-heartbeat
    namespace: default
roleRef:
  kind: Role
  name: pod-editor
  apiGroup: rbac.authorization.k8s.io