apiVersion: v1
kind: ConfigMap
metadata:
  name: python-script-configmap
data:
  script.py: |
    from azure.identity import ClientSecretCredential
    from azure.mgmt.resource import ResourceManagementClient
    import os

    # Authenticate with Azure
    credential = ClientSecretCredential(
        tenant_id=os.environ['AZURE_TENANT_ID'],
        client_id=os.environ['AZURE_CLIENT_ID'],
        client_secret=os.environ['AZURE_CLIENT_SECRET']
    )

    # Create a Resource Management client
    subscription_id = os.environ['AZURE_SUBSCRIPTION_ID']
    resource_client = ResourceManagementClient(credential, subscription_id)

    # Use the client to interact with Azure resources
    # For example, list resource groups
    for resource_group in resource_client.resource_groups.list():
        print(resource_group.name)