apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: python-azure
spec:
  params:
    - name: azure-subscription-id
      type: string
      description: Azure Subscription ID
    - name: azure-tenant-id
      type: string
      description: Azure Tenant ID
  volumes:
    - name: python-script
      configMap:
        name: python-script-configmap
  steps:
    - name: run-python-script
      image: python:3.9
      env:
        - name: AZURE_SUBSCRIPTION_ID
          value: $(params.azure-subscription-id)
        - name: AZURE_TENANT_ID
          value: $(params.azure-tenant-id)
      volumeMounts:
        - name: python-script
          mountPath: /workspace/python-script
      script: |
        pip install azure-identity azure-mgmt-resource
        python /workspace/python-script/script.py