apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-conftest
spec:
  resources:
    inputs:
    - name: source
      type: git
      targetPath: source
  params:
  - name: chart
    default: "."
  - name: policy
    default: "policy"
  - name: output
    default: "stdout"
  - name: args
    type: array
    default: []

  steps:
  - name: helm-conftest
    workingDir: /workspace/source
    image: instrumenta/helm-conftest:latest
    command:
      - helm
      - conftest
      - $(params.chart)
      - -p
      - $(params.policy)
      - -o
      - $(params.output)
      - $(params.args)
