apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helm-conftest
spec:
  inputs:
    resources:
    - name: source
      type: git
      targetPath: source
    params:
    - name: chart
      default: "."
    - name: policy
      default: "policy"
    - name: output
      default: "stdout"
    - name: args
      type: array
      default: []

  steps:
  - name: helm-conftest
    workingdir: /workspace/source
    image: instrumenta/helm-conftest:latest
    command:
      - helm
      - conftest
      - $(inputs.params.chart)
      - -p
      - $(inputs.params.policy)
      - -o      
      - $(inputs.params.output)
      - $(inputs.params.args)
