apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client-python
spec:
  workspaces:
    - name: kubeconfig-mount
      mountPath: /tekton/home/.kube
  params:
    - name: SCRIPT
      description: Python script to be executed
      type: string
      default: |
        #!/usr/bin/python

        import openshift as oc

        print('OpenShift client version: {}'.format(oc.get_client_version()))
        print('OpenShift server version: {}'.format(oc.get_server_version()))
  steps:
    - name: execute-script
      image: quay.io/vinamra2807/openshift-client-python:latest
      script: $(params.SCRIPT)
