apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eks-create-kubeconfig-pvc
spec:
  resources:
    requests:
      storage: 5M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: create-eks-cluster-
spec:
  taskRef:
    name: eks-cluster-create
  params:
  - name: cluster-name
    value: cluster-1
  - name: version
    value: "1.17"
  - name: region
    value: us-west-2
  - name: zones
    value: us-west-2a,us-west-2b,us-west-2c
  - name: nodegroup-name
    value: linux-nodes
  - name: node-type
    value: m5.xlarge
  - name: desired-nodes
    value: "2"
  - name: min-nodes
    value: "1"
  - name: max-nodes
    value: "2"
  workspaces:
  - name: secrets
    secret:
      secretName: aws-credentials
  - name: kubeconfig
    persistentVolumeClaim:
      claimName: eks-create-kubeconfig-pvc
