---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openshift-client
spec:
  inputs:
    resources:
      - name: source
        type: git
        optional: true
    params:
      - name: SCRIPT
        description: The OpenShift CLI arguments to run
        type: string
        default: "oc $@"
      - name: ARGS
        description: The OpenShift CLI arguments to run
        type: array
        default:
          - "help"
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: "$(inputs.params.SCRIPT)"
      args:
        - "$(inputs.params.ARGS)"
