apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubeval
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality, Kubernetes
    tekton.dev/tags: test
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/displayName: "kubeval"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This task makes it possible to use Kubeval within your Tekton pipelines.

    Kubeval is a tool used for validating Kubernetes configuration files. By
    default the task will recursively scan the provided repository for YAML
    files and validate them against the Kubernetes schemas.

  workspaces:
  - name: source
  params:
  - name: files
    default: "."
  - name: output
    default: "stdout"
  - name: args
    type: array
    default: []

  steps:
  - name: kubeval
    workingDir: $(workspaces.source.path)
    image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/garethr/kubeval:0.15.0" #tag: 0.15.0
    command:
      - kubeval
      - -d
      - $(params.files)
      - -o
      - $(params.output)
      - $(params.args)
