apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kn-create
spec:
  inputs:
    params:
    - name: kn-image
      description: kn binary image to be used to create Knative services
      default: gcr.io/knative-releases/github.com/knative/client/cmd/kn
    - name: service
      description: Name of the service to create
    - name: force
      description: Whether to force creation, which overrites existing services.
      default: "false"
    resources:
    - name: image
      type: image
  steps:
  - name: create
    image: $(inputs.params.kn-image)
    command: ["/ko-app/kn"]
    args:
    - service
    - create
    - $(inputs.params.service)
    - --image=$(inputs.resources.image.url)
    - --force=$(inputs.params.force)
    # TODO(jasonhall): Support limits/resources, env vars, etc.
