apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: black
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Code Quality
    tekton.dev/tags: formatter, python
    tekton.dev/displayName: "Python Black"
    tekton.dev/platforms: "linux/amd64"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This task can be used to format Python code
  workspaces:
    - name: shared-workspace
      description: >-
        The workspace containing python source code which we want to format.
  params:
    - name: args
      type: array
      description: extra args that needs to be appended
      default: ["--help"]
  steps:
    - name: format-python-code
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/cytopia/black:latest-0.2" #tag: latest-0.2
      workingDir: $(workspaces.shared-workspace.path)
      command:
        - black
      args:
        - $(params.args)
