apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: shp-taskrun
spec:
  taskRef:
    name: shp
  params:
    - name: SCRIPT
      value: |
        shp build list
        shp build run BUILD-NAME --follow