apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pluto
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Developer Tools
    tekton.dev/tags: pluto
    tekton.dev/displayName: "Fairwinds Pluto"
    tekton.dev/platforms: "linux/amd64"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    Pluto is a utility to help users find deprecated Kubernetes apiVersions in their code repositories and their helm releases.
  workspaces:
    - name: source
  params:
    - name: ARGS
      description: The pluto commands to run
      type: array
      default:
        - help
  steps:
    - name: pluto
      workingDir: $(workspaces.source.path)
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/quay.io/fairwinds/pluto:v5" #tag: v5
      command: ["/pluto"]
      args:
        - "$(params.ARGS)"