apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: python-boto3
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.18.0"
    tekton.dev/categories: CLI
    tekton.dev/tags: CLI, boto3, sdk
    tekton.dev/displayName: "python boto3 aws"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Executes a Python script using AWS Boto3 to manage and inspect AWS resources.
  params:
    - name: aws-region
      type: string
      default: "us-east-1"
      description: AWS Region
  volumes:
    - name: python-script
      configMap:
        name: python-script-configmap
  steps:
    - name: run-python-script
      image: docker.io/python:3.9
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: AWS_DEFAULT_REGION
          value: $(params.aws-region)
      volumeMounts:
        - name: python-script
          mountPath: /workspace/python-script
      script: |
        pip install boto3
        python3 /workspace/python-script/script.py
