apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-build
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "golang build"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
    ozone-in2tive-ai/imgurl: "/api/asset-bucket/taskicons/tekton.svg"
spec:
  description: >-
    This Task is Golang task to build Go projects.

  params:
    - name: package
      description: base package to build in
      type: string
    - name: packages
      description: "packages to build (default: ./cmd/...)"
      default: "./cmd/..."
      type: string
    - name: version
      description: golang version to use for builds
      default: "latest"
      type: string
    - name: flags
      description: flags to use for the test command
      type: string
      default: -v
    - name: GOOS
      type: string
      description: "running program's operating system target"
      default: linux
    - name: GOARCH
      type: string
      description: "running program's architecture target"
      default: amd64
    - name: GO111MODULE
      description: "value of module support"
      default: auto
      type: string
    - name: GOCACHE
      description: "Go caching directory path"
      type: string
      default: ""
    - name: GOMODCACHE
      type: string
      description: "Go mod caching directory path"
      default: ""
  workspaces:
    - name: source
  steps:
    - name: build
      image: docker.io/library/golang:$(params.version)
      workingDir: $(workspaces.source.path)
      script: |
        if [ ! -e $GOPATH/src/$(params.package)/go.mod ];then
           SRC_PATH="$GOPATH/src/$(params.package)"
           mkdir -p $SRC_PATH
           cp -R "$(workspaces.source.path)"/* $SRC_PATH
           cd $SRC_PATH
        fi
        go build $(params.flags) $(params.packages)
      env:
        - name: GOOS
          value: "$(params.GOOS)"
        - name: GOARCH
          value: "$(params.GOARCH)"
        - name: GO111MODULE
          value: "$(params.GO111MODULE)"
        - name: GOCACHE
          value: "$(params.GOCACHE)"
        - name: GOMODCACHE
          value: "$(params.GOMODCACHE)"
