apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-cluster-openshift-command
  namespace: default
spec:
  trigger:
    type: manual
  pipelineRef:
    name: pipeline-cluster-openshift-command
  resources:
    - name: cluster-one
      resourceRef:
        name: cluster-details