apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-cluster-openshift-command
  namespace: default
spec:
  resources:
    - name: cluster-one
      type: cluster
  tasks:
    - name: version
      taskRef:
        name: openshift-client-kubecfg
      resources:
        inputs:
          - name: clusterdetails
            resource: cluster-one
      params:
        - name: args
          value: "version --short"
    - name: user
      taskRef:
        name: openshift-client-kubecfg
      resources:
        inputs:
          - name: clusterdetails
            resource: cluster-one
      params:
        - name: args
          value: "whoami"
    - name: list
      taskRef:
        name: openshift-client-kubecfg
      resources:
        inputs:
          - name: clusterdetails
            resource: cluster-one
      params:
        - name: args
          value: "get pods"