apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kn-service-update
spec:
  resources:
  - name: image
    type: image
  params:
  - name: ARGS
    type: array
    description: Arguments to pass to kn CLI
    default:
      - "help"
  - name: IMAGE
    type: string
    description: The application image built by Buildah and used by kn task.
  tasks:
  - name: kn-service-update
    taskRef:
      name: kn
    params:
    - name: kn-image
      value: "gcr.io/knative-nightly/knative.dev/client/cmd/kn"
    - name: ARGS
      value:
        - "service"
        - "update"
        - "hello"
        - "--revision-name=hello-v2"
        - "--image=$(params.IMAGE)"
        - "--env=TARGET=v2"
        - "--service-account=kn-deployer-account"
