apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kn-service-update-
spec:
  serviceAccountName: kn-deployer-account
  pipelineRef:
    name: kn-service-update
  params:
    - name: IMAGE
      value: "gcr.io/knative-samples/helloworld-go"
