# ###
# This example demonstrates how to use an SSH key to connect to the Orka VM.
# You will first need to copy the public key to the VM and commit or save an
# image using `orka image commit` or `orka image save` and specify that base image.
# in the TaskRun or Pipeline as a param.
#
# You must specify the Task param ssh-key="true" in order to use an SSH key.
#
# ###
# You can create a Kubernetes secret with the SSH credentials as follows:
# kubectl create secret generic orka-ssh-key --from-file=id_rsa=/path/to/id_rsa --from-literal=username=<username>
# ###
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: use-ssh-key
spec:
  taskRef:
    name: orka-full
  params:
    - name: base-image
      value: catalina-ssh-key-30G.img
    - name: ssh-secret
      value: orka-ssh-key
    - name: ssh-password-key
      value: id_rsa
    - name: ssh-key
      value: "true"
    - name: verbose
      value: "true"
    - name: copy-build
      value: "false"
    - name: script
      value: |
        #!/usr/bin/env ruby
        puts "Hello macOS"
  workspaces:
    - name: orka
      emptyDir: {}
