apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-nodejs-taskrun
spec:
  # Use service account with git and image repo credentials
  serviceAccount: saacount
  taskRef:
    name: s2i
  inputs:
    resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/sclorg/nodejs-ex
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: quay.io/openshift-pipeline/nodejs-s2i-ex
