apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-conftest
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Testing
    tekton.dev/tags: test
    tekton.dev/displayName: "helm conftest"
    tekton.dev/platforms: "linux/amd64"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    These tasks make it possible to use Conftest within your Tekton pipelines

    Conftest is a tool for testing configuration files using Open Policy Agent.

  workspaces:
  - name: source
  params:
  - name: chart
    default: "."
  - name: policy
    default: "policy"
  - name: output
    default: "stdout"
  - name: args
    type: array
    default: []

  steps:
  - name: helm-conftest
    workingDir: $(workspaces.source.path)
    image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/instrumenta/helm-conftest"
    command:
      - helm
      - conftest
      - $(params.chart)
      - -p
      - $(params.policy)
      - -o
      - $(params.output)
      - $(params.args)
