---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: results-pipeline-run
spec:
  pipelineSpec:
    workspaces:
      - name: source-ws
      - name: cache-ws
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source-ws
        params:
          - name: url
            value: https://github.com/buildpacks/samples
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
      - name: buildpacks
        taskRef:
          name: buildpacks
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source-ws
          - name: cache
            workspace: cache-ws
        params:
          - name: APP_IMAGE
            value: <IMAGE_NAME>
          - name: SOURCE_SUBPATH
            value: apps/ruby-bundler
          - name: BUILDER_IMAGE
            value: docker.io/cnbs/sample-builder:bionic@sha256:26e1ce10dcd89bca754269d48a59c163cae1f2bc8a1cc02b103a4ad414da3a69
      - name: display-results
        runAfter:
          - buildpacks
        taskSpec:
          steps:
            - name: print
              image: docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
              script: |
                #!/usr/bin/env bash
                set -e
                echo "URL of created app image: $(params.URL)"
                echo "Digest of created app image: $(params.DIGEST)"
          params:
            - name: URL
            - name: DIGEST
        params:
          - name: URL
            value: $(tasks.buildpacks.results.APP_IMAGE_URL)
          - name: DIGEST
            value: $(tasks.buildpacks.results.APP_IMAGE_DIGEST)
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: results-ws-pvc
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: results-ws-pvc
