apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-webhook-slack
spec:
  params:
  - name: webhook-secret
    type: string
    description: secret name of the slack app webhook URL (key is url)
  - name: message
    type: string
    description: plain text message
  steps:
  - name: post
    image: gcr.io/tekton-releases/dogfooding/catalog-web-requests:latest
    script: |
      #!/bin/sh
      jq -n --arg text "${MESSAGE}" \
          '{text: $text}' \
          | /usr/bin/curl -H "Content-Type: application/json" -X POST -k -d@- $URL
    env:
    - name: URL
      valueFrom:
        secretKeyRef:
          name: $(params.webhook-secret)
          key: url
    - name: MESSAGE
      value: $(params.message)
