apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-channel-slack
spec:
  params:
  - name: token-secret
    type: string
    description: secret name of the slack app access token (key is token)
  - name: channel
    type: string
    description: channel id or channel name
  - name: message
    type: string
    description: plain text message
  steps:
  - name: post
    image: gcr.io/tekton-releases/dogfooding/catalog-web-requests:latest
    script: |
      #!/bin/sh
      jq -n --arg text "${MESSAGE}" --arg channel "${CHANNEL}" \
          '{text: $text, channel: $channel}' \
          | /usr/bin/curl -H "Content-Type: application/json" \
          -H 'Authorization: Bearer '$TOKEN \
          -X POST -k -d@- https://slack.com/api/chat.postMessage
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: $(params.token-secret)
          key: token
    - name: MESSAGE
      value: $(params.message)
    - name: CHANNEL
      value: $(params.channel)
