apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko
spec:
  inputs:
    params:
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile

    resources:
    - name: source
      type: git

  outputs:
    resources:
    - name: image
      type: image

  steps:
  - name: build-and-push
    workingdir: /workspace/source
    image: gcr.io/kaniko-project/executor
    # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
    # https://github.com/tektoncd/pipeline/pull/706
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=${inputs.params.DOCKERFILE}
    - --destination=${outputs.resources.image.url}
