apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kythe-go
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: annotations
    tekton.dev/displayName: "kythe go"
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/deprecated: "true"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This task generates annotations for source code.

    The kythe-go Task runs the Kythe Go extractor for the given
    package, placing the resulting kzips in the output workspace.

  workspaces:
    - name: output
      description: Output directory for kzip output files.
  params:
    - name: package
      type: string
      description: Go package to analyze.
  steps:
    - name: analyze-packages
      image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/gcr.io/kythe-public/golang-extractor:stable" #tag: stable
      env:
        - name: OUTPUT
          value: $(workspaces.output.path)
      args: ["$(params.package)"]
      securityContext:
        privileged: true
