apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: makisu
spec:
  inputs:
    params:
    - name: CONTEXTPATH
      description: Path to the build context.
      default: /workspace
    - name: PUSH_REGISTRY
      description: Registry to push image to.
      default: index.docker.io
    - name: REGISTRY_SECRET
      description: Secret containing information about the used regsitry.
      default: docker-registry-config

    resources:
    - name: source
      type: git

  outputs:
    resources:
    - name: image
      type: image

  steps:
  - name: build-and-push
    image: gcr.io/makisu-project/makisu:v0.1.10
    workingdir: /workspace/source
    command:
    - /makisu-internal/makisu
    - build
    - --push=$(inputs.params.PUSH_REGISTRY)
    - --registry-config=/registry-config
    - --modifyfs=true
    - --tag=$(outputs.resources.image.url)
    - --registry-config=/registry-config/registry.yaml
    - $(inputs.params.CONTEXTPATH)
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    volumeMounts:
    - name: registry-config
      mountPath: /registry-config
  volumes:
  - name: registry-config
    secret:
      secretName: $(inputs.params.REGISTRY_SECRET)
