apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-openshift-command-clusterresource
spec:
  inputs:
    resources:
      - name: clusterdetails
        type: cluster
  steps:
    - name: version
      image: quay.io/openshift-pipeline/openshift-cli
      command:
        - /usr/local/bin/oc
      args: ["--kubeconfig", "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig", "--context", "${inputs.resources.clusterdetails.name}", "version"]
    - name: pods
      image: quay.io/openshift-pipeline/openshift-cli
      command:
       - /usr/local/bin/oc
      args: ["--kubeconfig", "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig", "--context", "${inputs.resources.clusterdetails.name}", "get", "pods"]
    - name: user
      image: quay.io/openshift-pipeline/openshift-cli
      command:
        - /usr/local/bin/oc
      args: ["--kubeconfig", "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig", "--context", "${inputs.resources.clusterdetails.name}", "whoami"]
    - name: status
      image: quay.io/openshift-pipeline/openshift-cli
      command:
        - /usr/local/bin/oc
      args: ["--kubeconfig", "/workspace/${inputs.resources.clusterdetails.name}/kubeconfig", "--context", "${inputs.resources.clusterdetails.name}", "status"]
