apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: task-run-openshift-command-clusterresource
spec:
  taskRef:
    name: task-openshift-command-clusterresource
  inputs:
    resources:
      - name: clusterdetails
        resourceRef:
          name: cluster-details
