kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-pod-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: user
    namespace: default
roleRef:
  kind: Role
  name: get-pod-role
  apiGroup: rbac.authorization.k8s.io