apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cloudevent
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Networking
    tekton.dev/tags: cloud
    tekton.dev/platforms: "linux/amd64"
    tekton.dev/displayName: "cloudevent"
    ozone-in2tive-ai/imgurl: ""
spec:
  description: >-
    This Task send a single CloudEvent to a specified sink.
  params:
  - name: sink
    type: string
    description: Sink to send Event to
  - name: eventID
    type: string
    description: Event ID to use
  - name: eventType
    type: string
    description: The Event Type to use
    default: "tekton.cloudevent.message"
  - name: source
    type: string
    description: Source of the CloudEvent
    default: ""
  - name: data
    type: string
    description: The payload of the Event
    default: ""
  steps:
  - name: send
    image: "{{TEKTON_PUBLIC_REGISTRY_PREFIX}}/docker.io/iancoffey/sendevent-89c3de01c503ceb66b676a3e41c265ed"
    command: ["sendevent"]
    args:
    - "--event-id=$(params.eventID)"
    - "--event-type=$(params.eventType)"
    - "--source=$(params.source)"
    - "--data=$(params.data)"
    - "$(params.sink)"
