apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: curl
spec:
  inputs:
    params:
    - name: ARGS
      description: Arguments for curl.
      default: -i
    - name: URL
      description: URL to be curl'ed.
      default: "https://www.google.com"

  steps:
  - name: curl
    image: plerionio/curl
    command:
    - curl
    - ${inputs.params.URL}
    - ${inputs.params.ARGS}